version: '3.8'
services:
   minio:
      image: minio/minio
      container_name: minio
      ports:
          - "9000:9000"
          - "9090:9090"
      environment:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio123
      volumes:
          - ./minio-data:/data
      command: server /data --console-address ":9090"